-- Supabase-first store for the SharePoint-backed survey app.
-- This is intentionally insert-only for browser clients because the app keeps
-- MSAL authentication in v1 and does not issue Supabase-authenticated user JWTs.

create table if not exists public.survey_submissions (
  survey_id text primary key,
  source text not null default 'prelaunch',
  sharepoint_item_id bigint,
  sharepoint_list_name text,
  province text not null default '',
  municipality text not null default '',
  interviewer_name text not null default '',
  fingerprint text not null default '',
  phone_number text not null default '',
  submitted_at timestamptz not null,
  has_audio boolean not null default false,
  audio_question_ids text[] not null default '{}',
  status text not null default 'synced_to_supabase',
  is_duplicate boolean not null default false,
  duplicate_phone boolean not null default false,
  responses jsonb not null default '{}'::jsonb,
  custom_inputs jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  sharepoint_fields jsonb not null default '{}'::jsonb,
  sharepoint_receipt jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.survey_audio_files (
  id bigint generated by default as identity primary key,
  survey_id text not null references public.survey_submissions(survey_id) on delete cascade,
  question_id text not null,
  storage_bucket text not null default 'survey-audio',
  storage_path text not null,
  mime_type text not null default '',
  size_bytes bigint not null default 0,
  content_hash text not null default '',
  status text not null default 'uploaded',
  uploaded_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (survey_id, question_id),
  unique (storage_bucket, storage_path)
);

create table if not exists public.survey_audit_logs (
  log_id uuid primary key,
  survey_id text not null default '',
  surveyor_id text not null default '',
  action_type text not null default '',
  action_timestamp timestamptz not null,
  network_status text not null default '',
  sync_status text not null default 'synced_to_sharepoint',
  error_details text not null default '',
  app_version text not null default '',
  region text not null default '',
  province text not null default '',
  form_type text not null default '',
  retry_count integer not null default 0,
  created_from_offline boolean not null default false,
  device_info text not null default '',
  raw_metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists survey_submissions_province_idx on public.survey_submissions (province);
create index if not exists survey_submissions_municipality_idx on public.survey_submissions (municipality);
create index if not exists survey_submissions_interviewer_idx on public.survey_submissions (interviewer_name);
create index if not exists survey_submissions_submitted_at_idx on public.survey_submissions (submitted_at desc);
create index if not exists survey_audio_files_survey_id_idx on public.survey_audio_files (survey_id);
create index if not exists survey_audit_logs_action_timestamp_idx on public.survey_audit_logs (action_timestamp desc);

alter table public.survey_submissions enable row level security;
alter table public.survey_audio_files enable row level security;
alter table public.survey_audit_logs enable row level security;

drop policy if exists "browser insert survey submissions" on public.survey_submissions;
create policy "browser insert survey submissions"
on public.survey_submissions
for insert
to anon, authenticated
with check (source = 'prelaunch' and survey_id <> '');

drop policy if exists "browser insert survey audio files" on public.survey_audio_files;
create policy "browser insert survey audio files"
on public.survey_audio_files
for insert
to anon, authenticated
with check (survey_id <> '' and question_id <> '' and storage_bucket = 'survey-audio');

drop policy if exists "browser insert survey audit logs" on public.survey_audit_logs;
create policy "browser insert survey audit logs"
on public.survey_audit_logs
for insert
to anon, authenticated
with check (log_id is not null and action_type <> '');

grant usage on schema public to anon, authenticated;
grant insert on public.survey_submissions to anon, authenticated;
grant insert on public.survey_audio_files to anon, authenticated;
grant insert on public.survey_audit_logs to anon, authenticated;
grant usage on sequence public.survey_audio_files_id_seq to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'survey-audio',
  'survey-audio',
  false,
  52428800,
  array['audio/webm', 'audio/wav', 'audio/mpeg', 'audio/mp4', 'audio/ogg']
)
on conflict (id) do nothing;

drop policy if exists "browser insert survey audio objects" on storage.objects;
create policy "browser insert survey audio objects"
on storage.objects
for insert
to anon, authenticated
with check (
  bucket_id = 'survey-audio'
  and (storage.foldername(name))[1] = 'prelaunch'
);

alter table public.survey_submissions replica identity full;
alter table public.survey_audio_files replica identity full;
alter table public.survey_audit_logs replica identity full;

do $$
begin
  begin
    alter publication supabase_realtime add table public.survey_submissions;
  exception
    when duplicate_object then null;
  end;

  begin
    alter publication supabase_realtime add table public.survey_audio_files;
  exception
    when duplicate_object then null;
  end;

  begin
    alter publication supabase_realtime add table public.survey_audit_logs;
  exception
    when duplicate_object then null;
  end;
end $$;
